import { useRef, useState } from 'react';
import type { TitanEnvelope } from '../../types/training';
import { importTrainingPlan, parseTitanFile } from './importService';

const days = ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];
export function ImportPanel({ hasActivePlan, onImported }: { hasActivePlan: boolean; onImported: () => void }) {
  const input = useRef<HTMLInputElement>(null); const [preview,setPreview]=useState<TitanEnvelope>(); const [fileName,setFileName]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  async function select(file?: File) { if (!file) return; setMessage(''); try { setPreview(await parseTitanFile(file)); setFileName(file.name); } catch (error) { setPreview(undefined); setMessage(error instanceof Error?error.message:'Arquivo inválido.'); } }
  async function confirm() { if(!preview)return; setBusy(true); try { await importTrainingPlan(preview,fileName); setMessage('Ficha importada com sucesso. Seu histórico foi preservado.'); setPreview(undefined); onImported(); } catch(error){setMessage(error instanceof Error?error.message:'Falha ao importar.');} finally{setBusy(false);} }
  return <section className="card import-card"><div className="card-heading"><div className="icon-box">⇩</div><div><h2>Importar ficha</h2><p>Arquivo seguro no formato TITAN FIT 1.0</p></div></div><input ref={input} hidden type="file" accept=".json,.titan.json,application/json" onChange={(e)=>void select(e.target.files?.[0])}/><button className="button secondary" onClick={()=>input.current?.click()}>Selecionar .titan.json</button>{preview&&<div className="preview"><span className="eyebrow">PRÉVIA</span><h3>{preview.payload.name}</h3><p>por {preview.author}</p><div className="stats"><b>{preview.payload.sessions.length}<small>sessões</small></b><b>{preview.payload.sessions.reduce((n,s)=>n+s.exercises.length,0)}<small>exercícios</small></b><b>{preview.payload.durationWeeks??'—'}<small>semanas</small></b></div><p>{preview.payload.sessions.flatMap(s=>s.dayOfWeek===undefined?[]:[days[s.dayOfWeek]]).join(' · ')||'Dias flexíveis'}</p>{hasActivePlan&&<p className="notice">A ficha atual será arquivada.</p>}<p className="safe">✓ O histórico de execuções será preservado.</p><button disabled={busy} className="button primary" onClick={()=>void confirm()}>{busy?'Importando…':'Confirmar importação'}</button></div>}{message&&<p className="message" role="status">{message}</p>}<a className="demo-link" href={`${import.meta.env.BASE_URL}examples/titan-fit-demo.titan.json`} download>Baixar ficha demonstrativa</a></section>
}
