import type { Food } from './types';

// Biblioteca inicial voltada ao cotidiano brasileiro. Valores genéricos são referências
// nutricionais de preparações comuns; itens industrializados devem ser sobrescritos pelo
// rótulo da marca efetivamente consumida quando cadastrarmos produtos específicos.
export const FOOD_LIBRARY: Food[] = [
  { id: 'egg-whole-large', name: 'Ovo inteiro grande', unit: 'unit', referenceAmount: 1, macrosPerReference: { caloriesKcal: 72, proteinG: 6.3, carbohydrateG: 0.4, fatG: 4.8 } },
  { id: 'egg-white-large', name: 'Clara de ovo', unit: 'unit', referenceAmount: 1, macrosPerReference: { caloriesKcal: 17, proteinG: 3.6, carbohydrateG: 0.2, fatG: 0.1 } },
  { id: 'rice-white-cooked', name: 'Arroz branco cozido', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 130, proteinG: 2.7, carbohydrateG: 28.2, fatG: 0.3 } },
  { id: 'rice-brown-cooked', name: 'Arroz integral cozido', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 124, proteinG: 2.6, carbohydrateG: 25.8, fatG: 1 } },
  { id: 'beans-cooked', name: 'Feijão carioca cozido', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 76, proteinG: 4.8, carbohydrateG: 13.6, fatG: 0.5 } },
  { id: 'black-beans-cooked', name: 'Feijão preto cozido', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 77, proteinG: 4.5, carbohydrateG: 14, fatG: 0.5 } },
  { id: 'pasta-cooked', name: 'Macarrão cozido', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 157, proteinG: 5.8, carbohydrateG: 30.9, fatG: 0.9 } },
  { id: 'potato-cooked', name: 'Batata inglesa cozida', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 87, proteinG: 1.9, carbohydrateG: 20.1, fatG: 0.1 } },
  { id: 'sweet-potato-cooked', name: 'Batata-doce cozida', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 86, proteinG: 1.6, carbohydrateG: 20.1, fatG: 0.1 } },
  { id: 'cassava-cooked', name: 'Mandioca cozida', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 125, proteinG: 0.6, carbohydrateG: 30.1, fatG: 0.3 } },
  { id: 'couscous-cooked', name: 'Cuscuz de milho cozido', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 112, proteinG: 2.2, carbohydrateG: 25.3, fatG: 0.7 } },
  { id: 'tapioca-ready', name: 'Tapioca preparada sem recheio', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 230, proteinG: 0.2, carbohydrateG: 56, fatG: 0.1 } },
  { id: 'oats', name: 'Aveia em flocos', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 389, proteinG: 16.9, carbohydrateG: 66.3, fatG: 6.9 } },
  { id: 'bread-french', name: 'Pão francês', unit: 'g', referenceAmount: 50, macrosPerReference: { caloriesKcal: 150, proteinG: 4.5, carbohydrateG: 29.3, fatG: 1.6 } },
  { id: 'bread-slice', name: 'Pão de forma', unit: 'unit', referenceAmount: 1, macrosPerReference: { caloriesKcal: 67, proteinG: 2.4, carbohydrateG: 12.3, fatG: 1 } },
  { id: 'rap10', name: 'Wrap tipo Rap10', unit: 'unit', referenceAmount: 1, macrosPerReference: { caloriesKcal: 118, proteinG: 3.5, carbohydrateG: 20.4, fatG: 2.6 }, notes: 'Referência genérica. Preferir o rótulo da marca/versão consumida.' },
  { id: 'chicken-breast-grilled', name: 'Peito de frango grelhado', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 165, proteinG: 31, carbohydrateG: 0, fatG: 3.6 } },
  { id: 'chicken-shredded', name: 'Peito de frango desfiado', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 165, proteinG: 31, carbohydrateG: 0, fatG: 3.6 } },
  { id: 'patinho-ground-cooked', name: 'Patinho moído preparado', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 219, proteinG: 35.9, carbohydrateG: 0, fatG: 7.3 } },
  { id: 'beef-steak-grilled', name: 'Bife bovino grelhado', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 219, proteinG: 32, carbohydrateG: 0, fatG: 9.5 } },
  { id: 'ground-beef-cooked', name: 'Carne bovina moída preparada', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 220, proteinG: 26, carbohydrateG: 0, fatG: 12 } },
  { id: 'pork-loin-grilled', name: 'Lombo suíno grelhado', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 210, proteinG: 29, carbohydrateG: 0, fatG: 9 } },
  { id: 'tilapia-grilled', name: 'Tilápia grelhada', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 128, proteinG: 26, carbohydrateG: 0, fatG: 2.7 } },
  { id: 'sardines-canned', name: 'Sardinha em conserva drenada', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 208, proteinG: 25, carbohydrateG: 0, fatG: 11.5 } },
  { id: 'banana-medium', name: 'Banana média', unit: 'unit', referenceAmount: 1, macrosPerReference: { caloriesKcal: 105, proteinG: 1.3, carbohydrateG: 27, fatG: 0.4 } },
  { id: 'apple-medium', name: 'Maçã média', unit: 'unit', referenceAmount: 1, macrosPerReference: { caloriesKcal: 95, proteinG: 0.5, carbohydrateG: 25, fatG: 0.3 } },
  { id: 'orange-medium', name: 'Laranja média', unit: 'unit', referenceAmount: 1, macrosPerReference: { caloriesKcal: 62, proteinG: 1.2, carbohydrateG: 15.4, fatG: 0.2 } },
  { id: 'papaya', name: 'Mamão', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 43, proteinG: 0.5, carbohydrateG: 10.8, fatG: 0.3 } },
  { id: 'mango', name: 'Manga', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 60, proteinG: 0.8, carbohydrateG: 15, fatG: 0.4 } },
  { id: 'watermelon', name: 'Melancia', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 30, proteinG: 0.6, carbohydrateG: 7.6, fatG: 0.2 } },
  { id: 'avocado', name: 'Abacate', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 160, proteinG: 2, carbohydrateG: 8.5, fatG: 14.7 } },
  { id: 'milk-whole', name: 'Leite integral', unit: 'ml', referenceAmount: 200, macrosPerReference: { caloriesKcal: 122, proteinG: 6.3, carbohydrateG: 9.4, fatG: 6.5 } },
  { id: 'milk-powder', name: 'Leite em pó integral', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 496, proteinG: 25.8, carbohydrateG: 38.4, fatG: 26.7 } },
  { id: 'cheese-minas', name: 'Queijo minas frescal', unit: 'g', referenceAmount: 30, macrosPerReference: { caloriesKcal: 79, proteinG: 5.2, carbohydrateG: 1, fatG: 6.1 } },
  { id: 'mozzarella', name: 'Queijo muçarela', unit: 'g', referenceAmount: 30, macrosPerReference: { caloriesKcal: 90, proteinG: 6.7, carbohydrateG: 0.7, fatG: 6.8 } },
  { id: 'butter', name: 'Manteiga', unit: 'g', referenceAmount: 10, macrosPerReference: { caloriesKcal: 72, proteinG: 0.1, carbohydrateG: 0, fatG: 8.1 } },
  { id: 'margarine', name: 'Margarina', unit: 'g', referenceAmount: 10, macrosPerReference: { caloriesKcal: 72, proteinG: 0, carbohydrateG: 0.1, fatG: 8 } },
  { id: 'olive-oil', name: 'Azeite de oliva', unit: 'g', referenceAmount: 10, macrosPerReference: { caloriesKcal: 88, proteinG: 0, carbohydrateG: 0, fatG: 10 } },
  { id: 'tomato', name: 'Tomate cru', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 18, proteinG: 0.9, carbohydrateG: 3.9, fatG: 0.2 } },
  { id: 'lettuce', name: 'Alface crua', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 15, proteinG: 1.4, carbohydrateG: 2.9, fatG: 0.2 } },
  { id: 'carrot-cooked', name: 'Cenoura cozida', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 35, proteinG: 0.8, carbohydrateG: 8.2, fatG: 0.2 } },
  { id: 'broccoli-cooked', name: 'Brócolis cozido', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 35, proteinG: 2.4, carbohydrateG: 7.2, fatG: 0.4 } },
  { id: 'coffee-black', name: 'Café preto sem açúcar', unit: 'ml', referenceAmount: 100, macrosPerReference: { caloriesKcal: 2, proteinG: 0.1, carbohydrateG: 0, fatG: 0 } },
  { id: 'sugar', name: 'Açúcar', unit: 'g', referenceAmount: 10, macrosPerReference: { caloriesKcal: 40, proteinG: 0, carbohydrateG: 10, fatG: 0 } },
  { id: 'instant-coffee', name: 'Café solúvel', unit: 'g', referenceAmount: 5, macrosPerReference: { caloriesKcal: 6, proteinG: 0.6, carbohydrateG: 1, fatG: 0 } },
  { id: 'cocoa-powder', name: 'Cacau 100%', unit: 'g', referenceAmount: 10, macrosPerReference: { caloriesKcal: 23, proteinG: 2, carbohydrateG: 5.8, fatG: 1.4 } },
  { id: 'cinnamon', name: 'Canela em pó', unit: 'g', referenceAmount: 5, macrosPerReference: { caloriesKcal: 12, proteinG: 0.2, carbohydrateG: 4, fatG: 0.1 } },
  { id: 'water', name: 'Água', unit: 'ml', referenceAmount: 100, macrosPerReference: { caloriesKcal: 0, proteinG: 0, carbohydrateG: 0, fatG: 0 }, notes: 'Componente da preparação; não altera os macros.' },
  { id: 'popcorn-air', name: 'Pipoca sem óleo', unit: 'g', referenceAmount: 30, macrosPerReference: { caloriesKcal: 116, proteinG: 3.9, carbohydrateG: 23.3, fatG: 1.4 } },
  { id: 'cracker-cream', name: 'Biscoito cream cracker', unit: 'g', referenceAmount: 30, macrosPerReference: { caloriesKcal: 130, proteinG: 3, carbohydrateG: 21, fatG: 4 }, notes: 'Referência genérica; conferir rótulo da marca.' },
  { id: 'corn-cookie', name: 'Biscoito de maisena', unit: 'g', referenceAmount: 30, macrosPerReference: { caloriesKcal: 132, proteinG: 2.2, carbohydrateG: 23, fatG: 3.5 }, notes: 'Referência genérica; conferir rótulo da marca.' },
  { id: 'chocolate-milk-powder', name: 'Achocolatado em pó', unit: 'g', referenceAmount: 20, macrosPerReference: { caloriesKcal: 76, proteinG: 0.8, carbohydrateG: 17, fatG: 0.5 }, notes: 'Referência genérica; conferir rótulo da marca.' },
  { id: 'chocolate-milk', name: 'Bebida láctea achocolatada', unit: 'ml', referenceAmount: 200, macrosPerReference: { caloriesKcal: 160, proteinG: 5, carbohydrateG: 28, fatG: 3.2 }, notes: 'Referência genérica; conferir rótulo da marca.' },
  { id: 'soda-cola', name: 'Refrigerante tipo cola', unit: 'ml', referenceAmount: 200, macrosPerReference: { caloriesKcal: 84, proteinG: 0, carbohydrateG: 21, fatG: 0 }, notes: 'Referência genérica; conferir rótulo da marca.' },
  { id: 'orange-juice', name: 'Suco de laranja', unit: 'ml', referenceAmount: 200, macrosPerReference: { caloriesKcal: 90, proteinG: 1.4, carbohydrateG: 20.8, fatG: 0.4 } },
  { id: 'peanuts-roasted', name: 'Amendoim torrado', unit: 'g', referenceAmount: 30, macrosPerReference: { caloriesKcal: 176, proteinG: 7.7, carbohydrateG: 6.4, fatG: 14.9 } },
  { id: 'paçoca', name: 'Paçoca', unit: 'g', referenceAmount: 20, macrosPerReference: { caloriesKcal: 98, proteinG: 2.7, carbohydrateG: 10.5, fatG: 5.2 }, notes: 'Referência genérica; conferir rótulo da marca.' },
  { id: 'chocolate', name: 'Chocolate ao leite', unit: 'g', referenceAmount: 25, macrosPerReference: { caloriesKcal: 134, proteinG: 1.9, carbohydrateG: 14.8, fatG: 7.5 }, notes: 'Referência genérica; conferir rótulo da marca.' },
  { id: 'ice-cream', name: 'Sorvete de massa', unit: 'g', referenceAmount: 60, macrosPerReference: { caloriesKcal: 125, proteinG: 2.1, carbohydrateG: 14.5, fatG: 6.6 }, notes: 'Referência genérica; varia bastante por sabor e marca.' },
  { id: 'coxinha', name: 'Coxinha de frango', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 280, proteinG: 10, carbohydrateG: 30, fatG: 13 }, notes: 'Estimativa de preparação comum; receitas variam bastante.' },
  { id: 'cheese-bread', name: 'Pão de queijo', unit: 'g', referenceAmount: 50, macrosPerReference: { caloriesKcal: 165, proteinG: 3.5, carbohydrateG: 20, fatG: 8 }, notes: 'Estimativa de preparação comum; receitas variam.' },
  { id: 'pizza-mozzarella', name: 'Pizza de muçarela', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 266, proteinG: 11, carbohydrateG: 33, fatG: 10 }, notes: 'Estimativa genérica; cadastrar restaurante/marca quando necessário.' },
  { id: 'hamburger-sandwich', name: 'Hambúrguer / sanduíche simples', unit: 'g', referenceAmount: 100, macrosPerReference: { caloriesKcal: 260, proteinG: 13, carbohydrateG: 25, fatG: 12 }, notes: 'Estimativa genérica; composição varia muito.' },
];

export function getFood(foodId: string) {
  return FOOD_LIBRARY.find((food) => food.id === foodId);
}
