import fs from 'node:fs';

function replace(path, before, after) {
  const text = fs.readFileSync(path, 'utf8');
  if (!text.includes(before)) throw new Error(`Marker not found in ${path}: ${before.slice(0, 80)}`);
  fs.writeFileSync(path, text.replace(before, after));
}

const historyPath = 'src/features/history/HistoryPage.tsx';
let history = fs.readFileSync(historyPath, 'utf8');
history = history.replace("import type { WorkoutHistoryRecord } from './types';", "import type { HistorySet, WorkoutHistoryRecord } from './types';");
history = history.replace("function completedRecords(record: WorkoutHistoryRecord) { return record.exercises.reduce((sum, exercise) => sum + exercise.sets.length, 0); }", `function completedRecords(record: WorkoutHistoryRecord) { return record.exercises.reduce((sum, exercise) => sum + exercise.sets.length, 0); }\nfunction cardioPace(set: HistorySet) {\n  if (set.averagePace) return set.averagePace;\n  if (!set.durationSeconds || !set.distanceMeters || set.distanceMeters <= 0) return null;\n  const seconds = set.durationSeconds / (set.distanceMeters / 1000);\n  return \`${'${Math.floor(seconds / 60)}'}:${'${String(Math.round(seconds % 60)).padStart(2, \'0\')}'}\/km\`;\n}`);
history = history.replace("{item.averageHeartRate !== null && <strong>{item.averageHeartRate} bpm</strong>}", "{item.averagePace && <strong>{item.averagePace}</strong>}{!item.averagePace && cardioPace(item) && <strong>{cardioPace(item)}</strong>}{item.cardioZone && <strong>{item.cardioZone}</strong>}{item.averageHeartRate !== null && <strong>{item.averageHeartRate} bpm</strong>}{item.rpe !== undefined && item.rpe !== null && <strong>RPE {item.rpe}</strong>}{item.calories !== null && <strong>{item.calories} kcal</strong>}");
fs.writeFileSync(historyPath, history);

replace('src/features/health/HealthHubPage.tsx', "import { ProgressPage } from '../history/ProgressPage';", "import { HistoryPage } from '../history/HistoryPage';\nimport { ProgressPage } from '../history/ProgressPage';");
replace('src/features/health/HealthHubPage.tsx', "type HealthView = 'today' | 'evolution' | 'coach' | 'reports';", "type HealthView = 'today' | 'evolution' | 'history' | 'coach' | 'reports';");
replace('src/features/health/HealthHubPage.tsx', 'health-hub-switch-four', 'health-hub-switch-five');
replace('src/features/health/HealthHubPage.tsx', "      <button type=\"button\" role=\"tab\" aria-selected={view === 'coach'}", "      <button type=\"button\" role=\"tab\" aria-selected={view === 'history'} className={view === 'history' ? 'active' : ''} onClick={() => setView('history')}>Histórico</button>\n      <button type=\"button\" role=\"tab\" aria-selected={view === 'coach'}");
replace('src/features/health/HealthHubPage.tsx', "{view === 'today' ? <SamsungHealthPage /> : view === 'evolution' ? <ProgressPage refreshKey={refreshKey} /> : view === 'coach' ? <CoachPage /> : <ReportsPanel />}", "{view === 'today' ? <SamsungHealthPage /> : view === 'evolution' ? <ProgressPage refreshKey={refreshKey} /> : view === 'history' ? <HistoryPage refreshKey={refreshKey} /> : view === 'coach' ? <CoachPage /> : <ReportsPanel />}");

replace('src/features/cardio/evolution.ts', "type CardioEntry = { record: WorkoutHistoryRecord; exercise: WorkoutHistoryRecord['exercises'][number] };", "type CardioEntry = { record: WorkoutHistoryRecord; exercise: WorkoutHistoryRecord['exercises'][number] };\ntype CardioSession = { record: WorkoutHistoryRecord; entries: CardioEntry[] };");
replace('src/features/cardio/evolution.ts', `  const entries: CardioEntry[] = records\n    .filter((record) => {\n      const time = new Date(record.completedAt).getTime();\n      return time >= start && time < end;\n    })\n    .flatMap((record) => record.exercises\n      .filter((exercise) => exercise.exerciseType === 'cardio' || exercise.exerciseType === 'distance')\n      .map((exercise) => ({ record, exercise })));\n\n  const sessions = entries.length;`, `  const cardioRecords: CardioSession[] = records\n    .filter((record) => {\n      const time = new Date(record.completedAt).getTime();\n      return time >= start && time < end;\n    })\n    .map((record) => ({ record, entries: record.exercises\n      .filter((exercise) => exercise.exerciseType === 'cardio' || exercise.exerciseType === 'distance')\n      .map((exercise) => ({ record, exercise })) }))\n    .filter((session) => session.entries.length > 0);\n  const entries = cardioRecords.flatMap((session) => session.entries);\n\n  const sessions = cardioRecords.length;`);

replace('src/features/history/ProgressPage.tsx', "import { BodyEvolutionPage } from '../evolution/BodyEvolutionPage';", "import { buildCardioEvolution } from '../cardio/evolution';\nimport { BodyEvolutionPage } from '../evolution/BodyEvolutionPage';");
replace('src/features/history/ProgressPage.tsx', "const [view, setView] = useState<'body' | 'training'>('body');", "const [view, setView] = useState<'body' | 'training' | 'cardio'>('body');");
replace('src/features/history/ProgressPage.tsx', 'evolution-switch-two', 'evolution-switch-three');
replace('src/features/history/ProgressPage.tsx', "      <button type=\"button\" role=\"tab\" aria-selected={view === 'training'} className={view === 'training' ? 'active' : ''} onClick={() => setView('training')}>Treino</button>", "      <button type=\"button\" role=\"tab\" aria-selected={view === 'training'} className={view === 'training' ? 'active' : ''} onClick={() => setView('training')}>Treino</button>\n      <button type=\"button\" role=\"tab\" aria-selected={view === 'cardio'} className={view === 'cardio' ? 'active' : ''} onClick={() => setView('cardio')}>Cardio</button>");
replace('src/features/history/ProgressPage.tsx', "    {view === 'body' ? <BodyEvolutionPage /> : <PrHall refreshKey={refreshKey} />}", "    {view === 'body' ? <BodyEvolutionPage /> : view === 'training' ? <PrHall refreshKey={refreshKey} /> : <CardioEvolutionPanel refreshKey={refreshKey} />}");
replace('src/features/history/ProgressPage.tsx', "type PrEvent = { exerciseId: string; exerciseName: string; muscleGroup: string; completedAt: string; weightKg: number; repetitions: number; };", `function CardioEvolutionPanel({ refreshKey }: { refreshKey: number }) {\n  void refreshKey;\n  const report = buildCardioEvolution(loadWorkoutHistory(), 30);\n  return <section className=\"hero-card compact cardio-evolution-summary\"><span className=\"eyebrow\">CARDIO INTEGRADO · 30 DIAS</span><h2>Evolução cardiovascular</h2><p>Os números abaixo vêm somente do cardio registrado dentro dos seus treinos.</p><div className=\"summary-grid\"><div><span>Treinos com cardio</span><strong>{report.sessions}</strong></div><div><span>Tempo</span><strong>{Math.round(report.totalDurationSeconds / 60)} min</strong></div><div><span>Distância</span><strong>{report.totalDistanceMeters >= 1000 ? \`${'${(report.totalDistanceMeters / 1000).toFixed(1)}'} km\` : \`${'${Math.round(report.totalDistanceMeters)}'} m\`}</strong></div><div><span>FC média</span><strong>{report.averageHeartRate ? \`${'${report.averageHeartRate}'} bpm\` : '—'}</strong></div></div><div className=\"weekly-coach-priority\"><span className=\"eyebrow\">LEITURA TITAN</span><strong>{report.insight.title}</strong><p>{report.insight.message}</p></div></section>;\n}\n\ntype PrEvent = { exerciseId: string; exerciseName: string; muscleGroup: string; completedAt: string; weightKg: number; repetitions: number; };`);

let cardioTest = fs.readFileSync('tests/cardio-evolution.test.ts', 'utf8');
cardioTest = cardioTest.replace(/\n\}\);\s*$/, `\n  it('conta um treino com múltiplos blocos de cardio como uma única sessão', () => {\n    const record = cardioRecord('mixed', '2026-08-09T20:00:00', 2000, 1200, 140, 'Treino misto');\n    record.exercises.push({ ...record.exercises[0], exerciseId: 'mixed-cardio-2', name: 'Bike Zona 2', totalDistanceMeters: 5000, totalDurationSeconds: 1200 });\n    const report = buildCardioEvolution([record], 7, now);\n    expect(report.sessions).toBe(1);\n    expect(report.totalDistanceMeters).toBe(7000);\n    expect(report.totalDurationSeconds).toBe(2400);\n  });\n});\n`);
fs.writeFileSync('tests/cardio-evolution.test.ts', cardioTest);

let progressTest = fs.readFileSync('tests/ProgressPage.test.tsx', 'utf8');
progressTest = progressTest.replace("describe('ProgressPage v0.26.2'", "describe('ProgressPage v0.58.8'");
progressTest = progressTest.replace(/\n\}\);\s*$/, `\n  it('mantém cardio como visão de evolução integrada, sem criar módulo isolado', () => {\n    render(<ProgressPage refreshKey={0} />);\n    fireEvent.click(screen.getByRole('tab', { name: 'Cardio' }));\n    expect(screen.getByRole('heading', { name: 'Evolução cardiovascular' })).toBeInTheDocument();\n    expect(screen.getByText(/cardio registrado dentro dos seus treinos/i)).toBeInTheDocument();\n  });\n});\n`);
fs.writeFileSync('tests/ProgressPage.test.tsx', progressTest);

const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8')); pkg.version = '0.58.8'; fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');
const lock = JSON.parse(fs.readFileSync('package-lock.json', 'utf8')); lock.version = '0.58.8'; lock.packages[''].version = '0.58.8'; fs.writeFileSync('package-lock.json', JSON.stringify(lock, null, 2) + '\n');
let changelog = fs.readFileSync('CHANGELOG.md', 'utf8');
const marker = 'Este arquivo registra os cortes de versão oficiais do aplicativo. O histórico detalhado permanece nos commits e nas GitHub Releases.\n';
const section = `\n## v0.58.8 — Histórico e evolução integrados\n- Histórico volta a ficar acessível dentro do hub Saúde, sem criar uma nova aba principal.\n- Detalhe do cardio no histórico passa a exibir ritmo, zona realizada, RPE, calorias e demais métricas registradas.\n- Evolução ganha visão Cardio dentro do mesmo centro, explicitamente alimentada pelo cardio integrado aos treinos.\n- Contagem cardiovascular passa a considerar treinos com cardio, evitando duplicar uma sessão quando o mesmo treino possui mais de um bloco cardiovascular.\n- Musculação, PRs, composição corporal e histórico antigo permanecem compatíveis.\n`;
if (!changelog.includes('## v0.58.8 — Histórico e evolução integrados')) changelog = changelog.replace(marker, marker + section);
fs.writeFileSync('CHANGELOG.md', changelog);
