export type TitanMovementPattern = 'horizontal-push' | 'vertical-push' | 'horizontal-pull' | 'vertical-pull' | 'squat' | 'hinge' | 'knee-flexion' | 'elbow-flexion' | 'elbow-extension' | 'calf' | 'core';
export type TitanEquipment = 'barbell' | 'dumbbell' | 'machine' | 'cable' | 'bodyweight';

export type TitanCatalogExercise = {
  id: string;
  name: string;
  primaryMuscle: string;
  secondaryMuscles: string[];
  pattern: TitanMovementPattern;
  equipment: TitanEquipment[];
  minExperience: 'beginner' | 'intermediate' | 'advanced';
  repRange: [number, number];
  defaultRir: number;
  restSeconds: number;
  technique: string;
  commonMistakes: string[];
  substitutions: string[];
};

export const TITAN_EXERCISE_CATALOG: TitanCatalogExercise[] = [
  { id:'chest-press-machine', name:'Supino máquina', primaryMuscle:'Peitoral', secondaryMuscles:['Tríceps','Deltoide anterior'], pattern:'horizontal-push', equipment:['machine'], minExperience:'beginner', repRange:[6,12], defaultRir:2, restSeconds:120, technique:'Escápulas estáveis, peito alto e amplitude confortável.', commonMistakes:['Perder estabilidade escapular','Encurtar amplitude sem necessidade'], substitutions:['bench-press','dumbbell-bench-press'] },
  { id:'bench-press', name:'Supino reto com barra', primaryMuscle:'Peitoral', secondaryMuscles:['Tríceps','Deltoide anterior'], pattern:'horizontal-push', equipment:['barbell'], minExperience:'intermediate', repRange:[5,10], defaultRir:2, restSeconds:150, technique:'Pés firmes, escápulas retraídas e trajetória consistente.', commonMistakes:['Cotovelos excessivamente abertos','Perder tensão no tronco'], substitutions:['chest-press-machine','dumbbell-bench-press'] },
  { id:'dumbbell-bench-press', name:'Supino com halteres', primaryMuscle:'Peitoral', secondaryMuscles:['Tríceps','Deltoide anterior'], pattern:'horizontal-push', equipment:['dumbbell'], minExperience:'beginner', repRange:[6,12], defaultRir:2, restSeconds:120, technique:'Controle a descida e mantenha punhos alinhados.', commonMistakes:['Bater os halteres','Descer sem controle'], substitutions:['chest-press-machine','bench-press'] },
  { id:'lat-pulldown', name:'Puxada alta', primaryMuscle:'Dorsais', secondaryMuscles:['Bíceps','Redondo maior'], pattern:'vertical-pull', equipment:['cable','machine'], minExperience:'beginner', repRange:[6,12], defaultRir:2, restSeconds:120, technique:'Depressão escapular antes de puxar e tronco estável.', commonMistakes:['Usar balanço','Puxar atrás da nuca'], substitutions:['pull-up','machine-pulldown'] },
  { id:'machine-pulldown', name:'Puxada articulada', primaryMuscle:'Dorsais', secondaryMuscles:['Bíceps'], pattern:'vertical-pull', equipment:['machine'], minExperience:'beginner', repRange:[8,12], defaultRir:2, restSeconds:120, technique:'Conduza os cotovelos para baixo sem compensar com o tronco.', commonMistakes:['Excesso de impulso','Elevar ombros'], substitutions:['lat-pulldown','pull-up'] },
  { id:'pull-up', name:'Barra fixa', primaryMuscle:'Dorsais', secondaryMuscles:['Bíceps','Core'], pattern:'vertical-pull', equipment:['bodyweight'], minExperience:'intermediate', repRange:[5,10], defaultRir:2, restSeconds:150, technique:'Inicie com escápulas controladas e mantenha o corpo estável.', commonMistakes:['Kipping involuntário','Amplitude inconsistente'], substitutions:['lat-pulldown','machine-pulldown'] },
  { id:'seated-row', name:'Remada sentada', primaryMuscle:'Costas', secondaryMuscles:['Bíceps','Deltoide posterior'], pattern:'horizontal-pull', equipment:['cable','machine'], minExperience:'beginner', repRange:[6,12], defaultRir:2, restSeconds:120, technique:'Puxe com cotovelos e finalize sem hiperestender a lombar.', commonMistakes:['Balançar o tronco','Encolher os ombros'], substitutions:['chest-supported-row'] },
  { id:'chest-supported-row', name:'Remada apoiada', primaryMuscle:'Costas', secondaryMuscles:['Bíceps','Deltoide posterior'], pattern:'horizontal-pull', equipment:['machine','dumbbell'], minExperience:'beginner', repRange:[6,12], defaultRir:2, restSeconds:120, technique:'Mantenha peito apoiado e controle a protração e retração escapular.', commonMistakes:['Tirar o peito do apoio','Usar amplitude curta'], substitutions:['seated-row'] },
  { id:'machine-shoulder-press', name:'Desenvolvimento máquina', primaryMuscle:'Deltoides', secondaryMuscles:['Tríceps'], pattern:'vertical-push', equipment:['machine'], minExperience:'beginner', repRange:[6,12], defaultRir:2, restSeconds:120, technique:'Antebraços alinhados e amplitude sem desconforto.', commonMistakes:['Arquear excessivamente a lombar','Descer além da mobilidade disponível'], substitutions:['dumbbell-shoulder-press'] },
  { id:'dumbbell-shoulder-press', name:'Desenvolvimento com halteres', primaryMuscle:'Deltoides', secondaryMuscles:['Tríceps'], pattern:'vertical-push', equipment:['dumbbell'], minExperience:'intermediate', repRange:[6,12], defaultRir:2, restSeconds:120, technique:'Tronco firme e trajetória confortável para os ombros.', commonMistakes:['Perder alinhamento dos punhos','Exagerar no arco lombar'], substitutions:['machine-shoulder-press'] },
  { id:'hack-squat', name:'Agachamento hack', primaryMuscle:'Quadríceps', secondaryMuscles:['Glúteos'], pattern:'squat', equipment:['machine'], minExperience:'beginner', repRange:[6,12], defaultRir:2, restSeconds:150, technique:'Pés estáveis, joelhos acompanhando a direção dos pés.', commonMistakes:['Perder contato com a plataforma','Colapsar joelhos'], substitutions:['leg-press','barbell-squat'] },
  { id:'leg-press', name:'Leg press', primaryMuscle:'Quadríceps', secondaryMuscles:['Glúteos'], pattern:'squat', equipment:['machine'], minExperience:'beginner', repRange:[8,15], defaultRir:2, restSeconds:150, technique:'Controle a profundidade mantendo quadril estável no encosto.', commonMistakes:['Descolar o quadril','Travar joelhos agressivamente'], substitutions:['hack-squat','barbell-squat'] },
  { id:'barbell-squat', name:'Agachamento com barra', primaryMuscle:'Quadríceps', secondaryMuscles:['Glúteos','Core'], pattern:'squat', equipment:['barbell'], minExperience:'intermediate', repRange:[5,10], defaultRir:2, restSeconds:180, technique:'Brace antes da descida e mantenha equilíbrio sobre o pé.', commonMistakes:['Perder rigidez do tronco','Alterar trajetória por carga excessiva'], substitutions:['hack-squat','leg-press'] },
  { id:'romanian-deadlift', name:'Levantamento romeno', primaryMuscle:'Posteriores de coxa', secondaryMuscles:['Glúteos','Eretores da coluna'], pattern:'hinge', equipment:['barbell','dumbbell'], minExperience:'intermediate', repRange:[6,10], defaultRir:2, restSeconds:150, technique:'Leve o quadril para trás mantendo coluna neutra e carga próxima ao corpo.', commonMistakes:['Transformar em agachamento','Arredondar a lombar'], substitutions:['seated-leg-curl'] },
  { id:'seated-leg-curl', name:'Flexora sentada', primaryMuscle:'Posteriores de coxa', secondaryMuscles:[], pattern:'knee-flexion', equipment:['machine'], minExperience:'beginner', repRange:[8,15], defaultRir:2, restSeconds:90, technique:'Mantenha quadril apoiado e controle a fase excêntrica.', commonMistakes:['Levantar o quadril','Soltar a volta da carga'], substitutions:['romanian-deadlift'] },
  { id:'cable-curl', name:'Rosca no cabo', primaryMuscle:'Bíceps', secondaryMuscles:['Braquial'], pattern:'elbow-flexion', equipment:['cable'], minExperience:'beginner', repRange:[8,15], defaultRir:1, restSeconds:90, technique:'Cotovelos estáveis e amplitude controlada.', commonMistakes:['Balançar o tronco','Projetar cotovelos'], substitutions:['dumbbell-curl'] },
  { id:'dumbbell-curl', name:'Rosca com halteres', primaryMuscle:'Bíceps', secondaryMuscles:['Braquial'], pattern:'elbow-flexion', equipment:['dumbbell'], minExperience:'beginner', repRange:[8,15], defaultRir:1, restSeconds:90, technique:'Evite impulso e mantenha tensão durante a amplitude.', commonMistakes:['Usar balanço','Flexionar o ombro excessivamente'], substitutions:['cable-curl'] },
  { id:'cable-pushdown', name:'Tríceps na polia', primaryMuscle:'Tríceps', secondaryMuscles:[], pattern:'elbow-extension', equipment:['cable'], minExperience:'beginner', repRange:[8,15], defaultRir:1, restSeconds:90, technique:'Cotovelos próximos ao corpo e extensão controlada.', commonMistakes:['Abrir cotovelos','Usar o tronco para empurrar'], substitutions:['machine-dip'] },
  { id:'machine-dip', name:'Mergulho máquina', primaryMuscle:'Tríceps', secondaryMuscles:['Peitoral'], pattern:'elbow-extension', equipment:['machine'], minExperience:'beginner', repRange:[6,12], defaultRir:2, restSeconds:120, technique:'Mantenha ombros estáveis e controle a profundidade.', commonMistakes:['Descer além do conforto','Elevar ombros'], substitutions:['cable-pushdown'] },
  { id:'standing-calf-raise', name:'Panturrilha em pé', primaryMuscle:'Panturrilhas', secondaryMuscles:[], pattern:'calf', equipment:['machine','bodyweight'], minExperience:'beginner', repRange:[8,15], defaultRir:1, restSeconds:90, technique:'Use amplitude completa com pausa breve no alongamento.', commonMistakes:['Quicar','Reduzir amplitude'], substitutions:['seated-calf-raise'] },
  { id:'seated-calf-raise', name:'Panturrilha sentada', primaryMuscle:'Panturrilhas', secondaryMuscles:[], pattern:'calf', equipment:['machine'], minExperience:'beginner', repRange:[10,20], defaultRir:1, restSeconds:90, technique:'Controle a descida e evite repetições rápidas e curtas.', commonMistakes:['Quicar','Ignorar o alongamento'], substitutions:['standing-calf-raise'] },
  { id:'cable-crunch', name:'Crunch no cabo', primaryMuscle:'Abdômen', secondaryMuscles:[], pattern:'core', equipment:['cable'], minExperience:'beginner', repRange:[10,20], defaultRir:2, restSeconds:60, technique:'Flexione o tronco pelo abdômen sem puxar apenas com os braços.', commonMistakes:['Mover somente o quadril','Usar carga que elimina o controle'], substitutions:['plank'] },
  { id:'plank', name:'Prancha', primaryMuscle:'Core', secondaryMuscles:['Glúteos'], pattern:'core', equipment:['bodyweight'], minExperience:'beginner', repRange:[20,60], defaultRir:2, restSeconds:60, technique:'Mantenha costelas e pelve controladas e respire sob tensão.', commonMistakes:['Deixar quadril cair','Prender a respiração'], substitutions:['cable-crunch'] },
];

export const findCatalogExercise = (id: string) => TITAN_EXERCISE_CATALOG.find((exercise) => exercise.id === id);
