import type { TitanCatalogExercise, TitanEquipment, TitanMovementPattern } from './catalog';

type Seed=[string,string,string,string[],TitanMovementPattern,TitanEquipment[],[number,number],string[]];
const s=(id:string,name:string,muscle:string,secondary:string[],pattern:TitanMovementPattern,equipment:TitanEquipment[],reps:[number,number],subs:string[]=[]):Seed=>[id,name,muscle,secondary,pattern,equipment,reps,subs];
const technique=(pattern:TitanMovementPattern)=>({
'horizontal-push':'Mantenha escápulas estáveis, controle a descida e empurre sem perder o alinhamento.',
'vertical-push':'Mantenha tronco firme, punhos alinhados e use amplitude confortável para os ombros.',
'horizontal-pull':'Conduza os cotovelos para trás, controle as escápulas e evite impulso do tronco.',
'vertical-pull':'Inicie com controle escapular e conduza os cotovelos para baixo sem balançar o tronco.',
'squat':'Mantenha pés estáveis, joelhos acompanhando a direção dos pés e controle a profundidade.',
'hinge':'Leve o quadril para trás, mantenha coluna neutra e controle a fase excêntrica.',
'knee-flexion':'Mantenha quadril estável e controle a flexão e a volta da carga.',
'elbow-flexion':'Mantenha cotovelos estáveis e evite usar balanço para mover a carga.',
'elbow-extension':'Mantenha ombros e cotovelos estáveis e controle toda a extensão.',
'calf':'Use amplitude confortável, controle a descida e evite repetições com impulso.',
'core':'Mantenha pelve e costelas controladas e execute sem compensação lombar.'}[pattern]);
const mistakes=(pattern:TitanMovementPattern)=>pattern==='hinge'?['Arredondar a lombar','Usar carga que elimina o controle']:pattern==='squat'?['Perder estabilidade dos pés','Alterar a trajetória por excesso de carga']:pattern.includes('pull')?['Usar balanço','Encurtar a amplitude sem necessidade']:pattern.includes('push')?['Perder estabilidade','Usar amplitude desconfortável']:['Usar impulso','Perder controle da amplitude'];
const seeds:Seed[]=[
s('incline-machine-press','Supino inclinado máquina','Peitoral',['Tríceps','Deltoide anterior'],'horizontal-push',['machine'],[6,12],['incline-dumbbell-press']),s('incline-dumbbell-press','Supino inclinado com halteres','Peitoral',['Tríceps','Deltoide anterior'],'horizontal-push',['dumbbell'],[6,12],['incline-machine-press']),s('incline-barbell-press','Supino inclinado com barra','Peitoral',['Tríceps','Deltoide anterior'],'horizontal-push',['barbell'],[5,10],['incline-dumbbell-press']),s('decline-machine-press','Supino declinado máquina','Peitoral',['Tríceps'],'horizontal-push',['machine'],[6,12]),s('cable-chest-press','Supino no cabo','Peitoral',['Tríceps'],'horizontal-push',['cable'],[8,15]),s('push-up','Flexão de braços','Peitoral',['Tríceps','Core'],'horizontal-push',['bodyweight'],[8,20]),s('weighted-push-up','Flexão com carga','Peitoral',['Tríceps','Core'],'horizontal-push',['bodyweight'],[6,15]),s('cable-fly','Crucifixo no cabo','Peitoral',['Deltoide anterior'],'horizontal-push',['cable'],[10,20]),s('pec-deck','Peck deck','Peitoral',['Deltoide anterior'],'horizontal-push',['machine'],[10,20]),s('dumbbell-fly','Crucifixo com halteres','Peitoral',['Deltoide anterior'],'horizontal-push',['dumbbell'],[10,15]),
s('one-arm-lat-pulldown','Puxada unilateral','Dorsais',['Bíceps'],'vertical-pull',['cable'],[8,15]),s('neutral-lat-pulldown','Puxada neutra','Dorsais',['Bíceps'],'vertical-pull',['cable','machine'],[6,12]),s('underhand-lat-pulldown','Puxada supinada','Dorsais',['Bíceps'],'vertical-pull',['cable'],[6,12]),s('assisted-pull-up','Barra fixa assistida','Dorsais',['Bíceps'],'vertical-pull',['machine'],[6,12]),s('barbell-row','Remada curvada com barra','Costas',['Bíceps','Deltoide posterior'],'horizontal-pull',['barbell'],[5,10]),s('dumbbell-row','Remada unilateral com halter','Costas',['Bíceps'],'horizontal-pull',['dumbbell'],[6,12]),s('machine-row','Remada máquina','Costas',['Bíceps','Deltoide posterior'],'horizontal-pull',['machine'],[6,12]),s('tbar-row','Remada T','Costas',['Bíceps'],'horizontal-pull',['machine','barbell'],[6,12]),s('wide-cable-row','Remada aberta no cabo','Costas',['Deltoide posterior'],'horizontal-pull',['cable'],[8,15]),s('one-arm-cable-row','Remada unilateral no cabo','Costas',['Bíceps'],'horizontal-pull',['cable'],[8,15]),s('inverted-row','Remada invertida','Costas',['Bíceps','Core'],'horizontal-pull',['bodyweight'],[6,15]),s('straight-arm-pulldown','Pulldown braços estendidos','Dorsais',['Peitoral'],'vertical-pull',['cable'],[10,15]),
s('barbell-overhead-press','Desenvolvimento com barra','Deltoides',['Tríceps'],'vertical-push',['barbell'],[5,10]),s('arnold-press','Desenvolvimento Arnold','Deltoides',['Tríceps'],'vertical-push',['dumbbell'],[8,12]),s('landmine-press','Desenvolvimento landmine','Deltoides',['Peitoral','Tríceps'],'vertical-push',['barbell'],[8,15]),s('dumbbell-lateral-raise','Elevação lateral com halteres','Deltoides',[],'vertical-push',['dumbbell'],[10,20]),s('cable-lateral-raise','Elevação lateral no cabo','Deltoides',[],'vertical-push',['cable'],[10,20]),s('machine-lateral-raise','Elevação lateral máquina','Deltoides',[],'vertical-push',['machine'],[10,20]),s('rear-delt-fly','Crucifixo inverso máquina','Deltoides',['Costas'],'horizontal-pull',['machine'],[10,20]),s('cable-rear-delt-fly','Crucifixo inverso no cabo','Deltoides',['Costas'],'horizontal-pull',['cable'],[10,20]),s('face-pull','Face pull','Deltoides',['Costas'],'horizontal-pull',['cable'],[10,20]),
s('goblet-squat','Agachamento goblet','Quadríceps',['Glúteos','Core'],'squat',['dumbbell'],[8,15]),s('front-squat','Agachamento frontal','Quadríceps',['Glúteos','Core'],'squat',['barbell'],[5,10]),s('smith-squat','Agachamento Smith','Quadríceps',['Glúteos'],'squat',['machine'],[6,12]),s('bulgarian-split-squat','Agachamento búlgaro','Quadríceps',['Glúteos'],'squat',['dumbbell','bodyweight'],[8,15]),s('reverse-lunge','Afundo reverso','Quadríceps',['Glúteos'],'squat',['dumbbell','bodyweight'],[8,15]),s('walking-lunge','Passada','Quadríceps',['Glúteos'],'squat',['dumbbell','bodyweight'],[10,20]),s('step-up','Subida no banco','Quadríceps',['Glúteos'],'squat',['dumbbell','bodyweight'],[8,15]),s('leg-extension','Cadeira extensora','Quadríceps',[],'squat',['machine'],[10,20]),s('single-leg-press','Leg press unilateral','Quadríceps',['Glúteos'],'squat',['machine'],[8,15]),s('pendulum-squat','Agachamento pêndulo','Quadríceps',['Glúteos'],'squat',['machine'],[6,12]),
s('stiff-deadlift','Stiff','Posteriores de coxa',['Glúteos'],'hinge',['barbell','dumbbell'],[6,12]),s('conventional-deadlift','Levantamento terra','Posteriores de coxa',['Glúteos','Costas','Core'],'hinge',['barbell'],[3,8]),s('trap-bar-deadlift','Levantamento terra trap bar','Posteriores de coxa',['Glúteos','Quadríceps'],'hinge',['barbell'],[5,10]),s('good-morning','Good morning','Posteriores de coxa',['Glúteos','Core'],'hinge',['barbell'],[8,12]),s('lying-leg-curl','Mesa flexora','Posteriores de coxa',[],'knee-flexion',['machine'],[8,15]),s('standing-leg-curl','Flexora em pé','Posteriores de coxa',[],'knee-flexion',['machine'],[10,15]),s('single-leg-curl','Flexora unilateral','Posteriores de coxa',[],'knee-flexion',['machine'],[10,15]),s('nordic-curl','Nordic curl','Posteriores de coxa',['Glúteos'],'knee-flexion',['bodyweight'],[4,10]),
s('barbell-hip-thrust','Hip thrust com barra','Glúteos',['Posteriores de coxa'],'hinge',['barbell'],[6,12]),s('machine-hip-thrust','Hip thrust máquina','Glúteos',['Posteriores de coxa'],'hinge',['machine'],[8,15]),s('glute-bridge','Ponte de glúteos','Glúteos',['Posteriores de coxa'],'hinge',['bodyweight','dumbbell'],[10,20]),s('cable-pull-through','Pull through no cabo','Glúteos',['Posteriores de coxa'],'hinge',['cable'],[10,15]),s('cable-kickback','Coice no cabo','Glúteos',[],'hinge',['cable'],[12,20]),s('hip-abduction-machine','Cadeira abdutora','Glúteos',[],'hinge',['machine'],[12,25]),s('cable-hip-abduction','Abdução de quadril no cabo','Glúteos',[],'hinge',['cable'],[12,20]),
s('barbell-curl','Rosca direta com barra','Bíceps',['Braquial'],'elbow-flexion',['barbell'],[6,12]),s('ez-bar-curl','Rosca barra W','Bíceps',['Braquial'],'elbow-flexion',['barbell'],[6,12]),s('incline-dumbbell-curl','Rosca inclinada','Bíceps',['Braquial'],'elbow-flexion',['dumbbell'],[8,15]),s('preacher-curl','Rosca Scott','Bíceps',['Braquial'],'elbow-flexion',['machine','barbell'],[8,15]),s('machine-curl','Rosca máquina','Bíceps',['Braquial'],'elbow-flexion',['machine'],[8,15]),s('hammer-curl','Rosca martelo','Bíceps',['Braquial','Antebraços'],'elbow-flexion',['dumbbell'],[8,15]),s('rope-hammer-curl','Rosca martelo corda','Bíceps',['Braquial','Antebraços'],'elbow-flexion',['cable'],[8,15]),s('concentration-curl','Rosca concentrada','Bíceps',['Braquial'],'elbow-flexion',['dumbbell'],[10,15]),s('bayesian-curl','Rosca Bayesian','Bíceps',['Braquial'],'elbow-flexion',['cable'],[10,15]),
s('overhead-cable-extension','Tríceps francês no cabo','Tríceps',[],'elbow-extension',['cable'],[8,15]),s('dumbbell-overhead-extension','Tríceps francês com halter','Tríceps',[],'elbow-extension',['dumbbell'],[8,15]),s('skull-crusher','Tríceps testa','Tríceps',[],'elbow-extension',['barbell'],[8,15]),s('single-arm-pushdown','Tríceps unilateral na polia','Tríceps',[],'elbow-extension',['cable'],[10,15]),s('rope-pushdown','Tríceps corda','Tríceps',[],'elbow-extension',['cable'],[8,15]),s('close-grip-bench','Supino pegada fechada','Tríceps',['Peitoral'],'horizontal-push',['barbell'],[5,10]),s('bench-dip','Mergulho no banco','Tríceps',['Peitoral'],'elbow-extension',['bodyweight'],[8,20]),s('parallel-dip','Paralelas','Tríceps',['Peitoral'],'elbow-extension',['bodyweight'],[5,15]),
s('donkey-calf-raise','Panturrilha donkey','Panturrilhas',[],'calf',['machine'],[10,20]),s('leg-press-calf-raise','Panturrilha no leg press','Panturrilhas',[],'calf',['machine'],[10,20]),s('single-leg-calf-raise','Panturrilha unilateral','Panturrilhas',[],'calf',['bodyweight','dumbbell'],[10,20]),s('smith-calf-raise','Panturrilha no Smith','Panturrilhas',[],'calf',['machine'],[8,15]),
s('hanging-knee-raise','Elevação de joelhos suspenso','Core',['Flexores do quadril'],'core',['bodyweight'],[8,20]),s('hanging-leg-raise','Elevação de pernas suspenso','Core',['Flexores do quadril'],'core',['bodyweight'],[8,15]),s('reverse-crunch','Crunch reverso','Core',[],'core',['bodyweight'],[10,20]),s('dead-bug','Dead bug','Core',[],'core',['bodyweight'],[8,16]),s('bird-dog','Bird dog','Core',['Glúteos'],'core',['bodyweight'],[8,16]),s('side-plank','Prancha lateral','Core',[],'core',['bodyweight'],[20,60]),s('pallof-press','Pallof press','Core',[],'core',['cable'],[8,15]),s('ab-wheel','Roda abdominal','Core',['Dorsais'],'core',['bodyweight'],[6,15]),s('machine-crunch','Abdominal máquina','Core',[],'core',['machine'],[10,20]),
s('wrist-curl','Flexão de punho','Antebraços',[],'elbow-flexion',['dumbbell','barbell'],[12,20]),s('reverse-wrist-curl','Extensão de punho','Antebraços',[],'elbow-flexion',['dumbbell','barbell'],[12,20]),s('reverse-curl','Rosca inversa','Antebraços',['Bíceps'],'elbow-flexion',['barbell','cable'],[8,15]),s('farmers-walk','Caminhada do fazendeiro','Antebraços',['Trapézio','Core'],'core',['dumbbell'],[20,60]),s('barbell-shrug','Encolhimento com barra','Trapézio',['Antebraços'],'horizontal-pull',['barbell'],[8,15]),s('dumbbell-shrug','Encolhimento com halteres','Trapézio',['Antebraços'],'horizontal-pull',['dumbbell'],[8,15]),s('machine-shrug','Encolhimento máquina','Trapézio',['Antebraços'],'horizontal-pull',['machine'],[8,15]),
];
export const TITAN_EXTENDED_EXERCISE_CATALOG:TitanCatalogExercise[]=seeds.map(([id,name,primaryMuscle,secondaryMuscles,pattern,equipment,repRange,substitutions])=>({id,name,primaryMuscle,secondaryMuscles,pattern,equipment,minExperience:['conventional-deadlift','front-squat','barbell-row','nordic-curl','parallel-dip'].includes(id)?'intermediate':'beginner',repRange,defaultRir:pattern==='elbow-flexion'||pattern==='elbow-extension'||pattern==='calf'?1:2,restSeconds:['squat','hinge'].includes(pattern)?150:pattern.includes('push')||pattern.includes('pull')?120:90,technique:technique(pattern),commonMistakes:mistakes(pattern),substitutions}));
